#!/usr/bin/env perl

use strict;
use warnings;

use lib "/home/hosting_3bears/perl5/lib/perl5";

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('Sitegen');
